import { type NextPage } from "next";
import Head from "next/head";
import { HeroSection } from "../components/HeroSection";
import AboutSection from "../components/AboutSection";
// import SkillsSection from "../components/SkillsSection";
import ServicesSection from "../components/ServicesSection";
// import ProjectsSection from "../components/ProjectsSection";
import ProjectsSectionCS from "../components/ProjectsSectionCS";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kyuuari Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="absolute top-0 z-[-1]">
        <HeroSection />
        <AboutSection />
        <ServicesSection />
        {/* <SkillsSection /> */}
        <ProjectsSectionCS />
        <div className="h-5 py-5" />
        {/* <div className="h-screen w-screen ">Hellow World 2</div> */}
      </main>
    </>
  );
};

export default Home;
